#!/sbin/openrc-run
# Copyright 2015-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

output_log="${output_log:-/dev/null}"
error_log="${error_log:-${DRONE_LOGDIR}/server-error.log}"

name="${name:-Drone CI Server}"
command="/usr/bin/drone-server"
command_user="${command_use:-drone:drone}"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
retry="${retry:-TERM/30/KILL/5}"
start_stop_daemon_args="${SSD_OPTS}"

start_pre() {
	checkpath -d -m 0700 -o "${command_user}" \
        "${DRONE_DATADIR}" "${DRONE_LOGDIR}"
}
